baseURL = "https://antimaterie.ro/"
title = "Antimaterie"
theme = "zen"
languageCode = "ro-RO"

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true

[outputs]
home = [ "HTML", "RSS", "JSON", "SearchIndex" ]
section = [ "HTML", "RSS", "JSON" ]

[params]
alpine = false
blogSections = [ "distilat", "flux" ]
breadcrumbSections = [ "distilat", "flux" ]
cookieConsent = true
contact = "florin@athanor.ro"
copyright = '<!--Creative Commons License-->Conținut licențiat sub <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC-BY-SA 4.0</a> licence.<!--/Creative Commons License-->'
dateformat = "January 2, 2006"
description = "We are not Borg"
favicon = "/static"
feedlinks = true
footer = "We are not Borg"
icon = ""
image = "images/logo.png"
imageMaxWidth = "400"
logoWidth = 200
logoHeight = 100
internalPagination = false
jquery = false
languageDir = "ltr"
logo = true
mainSections = [ "flux" ]
math = false
menuInHeader = true
microUsername = ""
mobileMenu = true
mobileMenuOutline = true
piwikTrackerUrl = "antimaterie.matomo.cloud/"
piwikSiteID = "1"
plausibleSiteID = "1"
plausibleTrackerURL = ""
poweredby = true
privacyPolicyUrl = ""
relatedposts = true
sassTranspiler = "dartsass"
searchLimit = 20
sidebar = false
siteName = false
submitted = true
umbrella = true
ShowShareButtons = true

[[menu.main]]
Name = "Flux"
weight = 2
pageRef = "/flux"

[[menu.main]]
Name = "Distilat"
weight = 3
pageRef = "/distilat"

[[menu.main]]
Name = "Abonare"
weight = 4
pageRef = "/abonare"

[[menu.main]]
Name = "Autori"
weight = 5
pageRef = "/authors"

  [params.author]

  [params.podcast]
  explicit = "false/true"
  block = "no/yes"
  complete = "no/yes"
  type = "episodic/serial"
  local = false
  preload = "none/metadata/auto"

    [params.podcast.category]
    subcategories = [ ]

    [params.podcast.owner]
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title=true
